// Package web serves a browser UI for the statusd snapshot: it lists tmux
// sessions, streams a selected pane's output over a WebSocket, and relays
// keyboard input back into that pane.
package web

import (
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sync"
	"time"

	"github.com/leolin310148/tmact/internal/agentusage"
	"github.com/leolin310148/tmact/internal/dispatch"
	"github.com/leolin310148/tmact/internal/statusd"
	"github.com/leolin310148/tmact/internal/stt"
	"github.com/leolin310148/tmact/internal/tmux"
)

// all:static so the directory still embeds (and the binary still compiles) on a
// fresh checkout where internal/web/static holds only .gitkeep — the React UI
// build output is generated by `make web`, not committed. Once built, the
// hashed assets under static/ are embedded and served normally.
//
//go:embed all:static
var staticFS embed.FS

const (
	wsCaptureInterval  = 200 * time.Millisecond
	wsCaptureTimeout   = 2 * time.Second
	wsCaptureLines     = 2000
	wsReadLimit        = 1 << 20
	wsPingInterval     = 25 * time.Second
	wsPingTimeout      = 10 * time.Second
	wsWriteTimeout     = 5 * time.Second
	peerRequestTimeout = 10 * time.Second
	peerSlowRequest    = 1 * time.Second

	maxAudioUploadBytes = 25 << 20
	maxImageUploadBytes = 25 << 20
	maxFileUploadBytes  = 100 << 20
)

// Server is the daemon-side HTTP server for the web UI.
type Server struct {
	// Addr is the TCP listen address, e.g. "0.0.0.0:7890". May be empty when
	// the server is only being served over a unix socket.
	Addr string
	// SocketPath is a unix-domain socket path the server also listens on,
	// e.g. "/tmp/tmact-statusd.sock". Used as a cheap local-only IPC for the
	// CLI. Either Addr, SocketPath, or both may be set.
	SocketPath string
	// Store is the in-memory snapshot store the daemon publishes to. Required
	// for /api/snapshot and /api/snapshot/stream; absent only in narrow tests
	// that exercise other endpoints.
	Store *statusd.Store
	// CapturePane captures pane output; defaults to tmux.CapturePane.
	CapturePane func(target string, lines int) (string, error)
	// CapturePaneContext captures pane output with cancellation support;
	// defaults to tmux.CapturePaneContext. CapturePane is still honored for
	// tests and custom callers that do not need context cancellation.
	CapturePaneContext func(ctx context.Context, target string, lines int) (string, error)
	// PaneCaptureTimeout bounds each pane-stream capture; defaults to
	// wsCaptureTimeout.
	PaneCaptureTimeout time.Duration
	// SendText inserts literal text into a pane; defaults to tmux.PasteText.
	SendText func(target, text string, enter bool) error
	// SendKey sends one tmux key to a pane; defaults to tmux.SendKeys.
	SendKey func(target, key string) error
	// ClearPane clears the visible pane and its tmux scrollback history.
	ClearPane func(target string) error
	// STTProviderPath is the local provider config path; defaults to
	// ~/.tmact/stt_provider.json.
	STTProviderPath string
	// LoadSTTProvider loads speech-to-text provider config; defaults to reading
	// STTProviderPath.
	LoadSTTProvider func() (stt.ProviderConfig, error)
	// SaveSTTProvider persists speech-to-text provider config; defaults to
	// writing STTProviderPath.
	SaveSTTProvider func(stt.ProviderConfig) error
	// HTTPClient is used for transcription API calls; defaults to a 60s client.
	HTTPClient *http.Client
	// PasteImageDir is where pasted clipboard images are written; defaults to
	// <os.TempDir()>/tmact-paste.
	PasteImageDir string
	// UploadDir is where explicit browser file uploads are written; defaults to
	// <os.TempDir()>/tmact-upload.
	UploadDir string
	// Logf logs server-side diagnostics; defaults to writing to stderr, which
	// statusd routes to its log file.
	Logf func(format string, args ...any)
	// BuildTime is the VCS timestamp shown in the settings panel.
	BuildTime string
	// Peers is the set of remote statusd instances reachable for federated pane
	// access. Pane ids with a "<name>@" prefix matching a peer name are bridged
	// with short HTTP diff/input requests instead of acted on locally.
	Peers []statusd.Peer
	// CostPeers is the set of remote tmact instances that only contribute
	// token-spend from /api/agent-usage. They are not pane peers.
	CostPeers []statusd.Peer
	// UsageEnabled turns on the quota / rate-limit refresher (reads agent OAuth
	// credentials read-only and hits provider usage endpoints on a slow
	// ticker). The /api/agent-usage endpoint is served whenever UsageEnabled OR
	// SpendEnabled is on, so a machine can run cost-only with quota off.
	UsageEnabled bool
	// UsageInterval is how often quota / rate-limit usage is refreshed (hits
	// provider endpoints); defaults to 5m.
	UsageInterval time.Duration
	// SpendInterval is how often token spend (local logs + peers) is recomputed
	// (cheap local disk scan); defaults to 1h, independent of UsageInterval.
	SpendInterval time.Duration
	// SpendEnabled turns on the token-spend (cost) computation and its merge
	// into the agent-usage panel. When false, the panel shows quota only — no
	// local disk scan, no peer spend fetch. Lets a peer (or any machine) opt
	// out of cost so it neither computes nor contributes spend to a hub's
	// total — or, inversely, run cost-only with UsageEnabled=false.
	SpendEnabled bool
	// FetchUsage fetches agent usage; defaults to agentusage.Fetch (all
	// providers). Overridable in tests.
	FetchUsage func(ctx context.Context) agentusage.Snapshot
	// DispatchRun handles /api/dispatch-work; defaults to dispatch.Run.
	DispatchRun func(dispatch.Options) (dispatch.Report, error)
	// WebPushVAPIDPublicKey / WebPushVAPIDPrivateKey / WebPushVAPIDSubject
	// configure same-origin PWA Web Push. Empty values fall back to
	// TMACT_WEBPUSH_VAPID_* environment variables.
	WebPushVAPIDPublicKey  string
	WebPushVAPIDPrivateKey string
	WebPushVAPIDSubject    string
	// WebPushSubscriptionsPath stores browser PushSubscription JSON keyed by
	// endpoint. Empty falls back to TMACT_WEBPUSH_SUBSCRIPTIONS_PATH, then
	// ~/.tmact/webpush_subscriptions.json.
	WebPushSubscriptionsPath string
	// WebPushHTTPClient sends push POSTs; defaults to http.DefaultClient.
	WebPushHTTPClient webpushHTTPClient

	// usage caches the latest quota snapshot the usage refresher produces.
	usage usageCache
	// spend caches the latest merged (local + peers) per-provider token spend,
	// refreshed on its own faster cadence and merged with the quota snapshot at
	// serve time.
	spend spendCache
	// peerSpend caches each peer's last-known per-provider spend so a briefly
	// unreachable peer keeps contributing its last
	// figure to the merged total instead of dropping out and making the number
	// jump. Keyed by peer name.
	peerSpend peerSpendCache

	// paneDiff caches the latest local capture per pane for /api/pane/diff.
	paneDiff paneDiffCache
	// pushMu serializes reads/writes to the subscription JSON file.
	pushMu sync.Mutex
}

// lookupPeer returns the peer config for name, or false when none matches.
func (s *Server) lookupPeer(name string) (statusd.Peer, bool) {
	for _, p := range s.Peers {
		if p.Name == name {
			return p, true
		}
	}
	return statusd.Peer{}, false
}

func (s *Server) capture() func(string, int) (string, error) {
	if s.CapturePane != nil {
		return s.CapturePane
	}
	return tmux.CapturePane
}

func (s *Server) captureContext() func(context.Context, string, int) (string, error) {
	if s.CapturePaneContext != nil {
		return s.CapturePaneContext
	}
	if s.CapturePane != nil {
		return func(_ context.Context, target string, lines int) (string, error) {
			return s.CapturePane(target, lines)
		}
	}
	return tmux.CapturePaneContext
}

func (s *Server) paneCaptureTimeout() time.Duration {
	if s.PaneCaptureTimeout > 0 {
		return s.PaneCaptureTimeout
	}
	return wsCaptureTimeout
}

func (s *Server) sendText() func(string, string, bool) error {
	if s.SendText != nil {
		return s.SendText
	}
	return tmux.PasteText
}

func (s *Server) sendKey() func(string, string) error {
	if s.SendKey != nil {
		return s.SendKey
	}
	return func(target, key string) error { return tmux.SendKeys(target, []string{key}) }
}

func (s *Server) clearPane() func(string) error {
	if s.ClearPane != nil {
		return s.ClearPane
	}
	return tmux.ClearPane
}

func (s *Server) sttProvider() (stt.ProviderConfig, error) {
	if s.LoadSTTProvider != nil {
		cfg, err := s.LoadSTTProvider()
		if err != nil {
			return stt.ProviderConfig{}, err
		}
		if err := cfg.NormalizeAndValidate(); err != nil {
			return stt.ProviderConfig{}, err
		}
		return cfg, nil
	}
	return stt.LoadProvider(s.STTProviderPath)
}

func (s *Server) saveSTT() func(stt.ProviderConfig) error {
	if s.SaveSTTProvider != nil {
		return s.SaveSTTProvider
	}
	return func(cfg stt.ProviderConfig) error {
		return stt.SaveProvider(s.STTProviderPath, cfg)
	}
}

func (s *Server) pasteImageDir() string {
	if s.PasteImageDir != "" {
		return s.PasteImageDir
	}
	return filepath.Join(os.TempDir(), "tmact-paste")
}

func (s *Server) uploadDir() string {
	if s.UploadDir != "" {
		return s.UploadDir
	}
	return filepath.Join(os.TempDir(), "tmact-upload")
}

func (s *Server) httpClient() *http.Client {
	if s.HTTPClient != nil {
		return s.HTTPClient
	}
	return &http.Client{Timeout: 60 * time.Second}
}

func (s *Server) logf(format string, args ...any) {
	if s.Logf != nil {
		s.Logf(format, args...)
		return
	}
	fmt.Fprintf(os.Stderr, "statusd web: "+format+"\n", args...)
}

func (s *Server) dispatchRun() func(dispatch.Options) (dispatch.Report, error) {
	if s.DispatchRun != nil {
		return s.DispatchRun
	}
	return dispatch.Run
}

// Handler builds the HTTP routes without binding a socket; useful for tests.
func (s *Server) Handler() http.Handler {
	mux := http.NewServeMux()

	sub, err := fs.Sub(staticFS, "static")
	if err != nil {
		panic(err) // embedded path is fixed at build time
	}
	// /sw.js is served with a content-hash cache key so any change to an
	// embedded static asset busts the browser's service-worker cache without
	// requiring a manual version bump.
	mux.HandleFunc("/sw.js", s.handleServiceWorker)
	mux.Handle("/", http.FileServer(http.FS(sub)))
	mux.HandleFunc("/api/snapshot", s.handleSnapshot)
	mux.HandleFunc("/api/snapshot/stream", s.handleSnapshotStream)
	mux.HandleFunc("/api/agent-usage", s.handleAgentUsage)
	mux.HandleFunc("/api/health", s.handleHealth)
	mux.HandleFunc("/api/version", s.handleVersion)
	mux.HandleFunc("/api/vapid-public-key", s.handleVAPIDPublicKey)
	mux.HandleFunc("/api/subscribe", s.handlePushSubscribe)
	mux.HandleFunc("/api/unsubscribe", s.handlePushUnsubscribe)
	mux.HandleFunc("/api/push", s.handlePush)
	mux.HandleFunc("/api/frontend-logs", s.handleFrontendLogs)
	mux.HandleFunc("/api/settings/stt", s.handleSTTSettings)
	mux.HandleFunc("/api/transcribe", s.handleTranscribe)
	mux.HandleFunc("/api/paste-image", s.handlePasteImage)
	mux.HandleFunc("/api/upload-file", s.handleUploadFile)
	mux.HandleFunc("/api/image", s.handleImage)
	mux.HandleFunc("/api/markdown", s.handleMarkdown)
	mux.HandleFunc("/api/file", s.handleFile)
	mux.HandleFunc("/api/files/check", s.handleFilesCheck)
	mux.HandleFunc("/api/dispatch-work", s.handleDispatchWork)
	mux.HandleFunc("/api/pane/diff", s.handlePaneDiff)
	mux.HandleFunc("/api/pane/input", s.handlePaneInput)
	mux.HandleFunc("/ws/pane", s.handlePaneWS)
	return mux
}

var (
	staticHashOnce sync.Once
	staticHashVal  string
	swBodyOnce     sync.Once
	swBodyVal      []byte
	swBodyErr      error
	cacheNameRe    = regexp.MustCompile(`tmact-app-shell-v[0-9A-Za-z]+`)
)

// staticAssetHash returns a short content hash covering every embedded static
// file. Any edit under internal/web/static/ flips the hash, which propagates
// into the service worker's CACHE_NAME so the browser refetches the shell.
func staticAssetHash() string {
	staticHashOnce.Do(func() {
		h := sha256.New()
		_ = fs.WalkDir(staticFS, "static", func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			f, err := staticFS.Open(path)
			if err != nil {
				return err
			}
			defer f.Close()
			_, _ = io.WriteString(h, path+"\x00")
			_, _ = io.Copy(h, f)
			_, _ = h.Write([]byte{0})
			return nil
		})
		staticHashVal = hex.EncodeToString(h.Sum(nil))[:12]
	})
	return staticHashVal
}

func (s *Server) handleServiceWorker(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		w.Header().Set("Allow", "GET, HEAD")
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	swBodyOnce.Do(func() {
		raw, err := fs.ReadFile(staticFS, "static/sw.js")
		if err != nil {
			swBodyErr = err
			return
		}
		swBodyVal = cacheNameRe.ReplaceAll(raw, []byte("tmact-app-shell-"+staticAssetHash()))
	})
	if swBodyErr != nil {
		http.Error(w, "service worker unavailable", http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
	// no-store keeps the SW script itself fresh; the SW manages its own cache.
	w.Header().Set("Cache-Control", "no-store")
	if r.Method == http.MethodHead {
		return
	}
	_, _ = w.Write(swBodyVal)
}

func (s *Server) handleVersion(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		writeJSONError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	_ = json.NewEncoder(w).Encode(struct {
		BuildTime string `json:"build_time"`
		AssetHash string `json:"asset_hash"`
	}{BuildTime: s.BuildTime, AssetHash: staticAssetHash()})
}

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		w.Header().Set("Allow", http.MethodGet)
		writeJSONError(w, http.StatusMethodNotAllowed, "method not allowed")
		return
	}
	if s.Store == nil {
		writeJSON(w, http.StatusServiceUnavailable, map[string]any{
			"ok":                 false,
			"snapshot_available": false,
			"error":              "snapshot store not configured",
		})
		return
	}
	snap, ok := s.Store.Latest()
	if !ok {
		writeJSON(w, http.StatusServiceUnavailable, map[string]any{
			"ok":                 false,
			"snapshot_available": false,
			"error":              "snapshot not yet available",
		})
		return
	}

	now := time.Now()
	age := now.Sub(snap.Timestamp)
	if snap.Timestamp.IsZero() {
		age = 0
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"ok":                 !snap.IsStale(now),
		"snapshot_available": true,
		"snapshot_ts":        snap.Timestamp,
		"snapshot_age_ms":    age.Milliseconds(),
		"interval_ms":        snap.IntervalMS,
		"stale_after_ms":     snap.StaleAfterMS,
		"summary":            snap.Summary,
		"error_count":        len(snap.Errors),
	})
}

// Serve runs the HTTP server until ctx is cancelled, then shuts down
// gracefully. It serves the same handler on the TCP Addr (if set) and on the
// unix SocketPath (if set); at least one must be configured.
func (s *Server) Serve(ctx context.Context) error {
	if s.Addr == "" && s.SocketPath == "" {
		return errors.New("web.Server: Addr or SocketPath must be set")
	}

	srv := &http.Server{
		Handler:           s.Handler(),
		ReadHeaderTimeout: 10 * time.Second,
	}

	go s.runUploadsGC(ctx)
	// Quota and cost are independently gated: a peer can run cost-only (spend
	// served for a hub to aggregate) without ever hitting the rate-limited
	// quota endpoints.
	if s.UsageEnabled {
		go s.runUsageRefresh(ctx)
	}
	if s.SpendEnabled {
		go s.runSpendRefresh(ctx)
	}

	listeners, err := s.listeners()
	if err != nil {
		return err
	}

	errCh := make(chan error, len(listeners))
	var wg sync.WaitGroup
	for _, ln := range listeners {
		wg.Add(1)
		go func(ln net.Listener) {
			defer wg.Done()
			errCh <- srv.Serve(ln)
		}(ln)
	}

	select {
	case <-ctx.Done():
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = srv.Shutdown(shutdownCtx)
		wg.Wait()
		if s.SocketPath != "" {
			_ = os.Remove(s.SocketPath)
		}
		return nil
	case err := <-errCh:
		_ = srv.Shutdown(context.Background())
		wg.Wait()
		if s.SocketPath != "" {
			_ = os.Remove(s.SocketPath)
		}
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	}
}

// listeners opens the configured TCP and/or unix-socket listeners. A stale
// unix socket from a crashed prior run is removed first; the socket is created
// with 0600 perms so other local users cannot send keys.
func (s *Server) listeners() ([]net.Listener, error) {
	var out []net.Listener
	if s.Addr != "" {
		ln, err := net.Listen("tcp", s.Addr)
		if err != nil {
			return nil, fmt.Errorf("listen tcp %s: %w", s.Addr, err)
		}
		out = append(out, ln)
	}
	if s.SocketPath != "" {
		// Best-effort remove of a stale socket from a previous run. Ignore
		// failure here so we surface a clearer error from Listen below.
		_ = os.Remove(s.SocketPath)
		ln, err := net.Listen("unix", s.SocketPath)
		if err != nil {
			for _, prev := range out {
				_ = prev.Close()
			}
			return nil, fmt.Errorf("listen unix %s: %w", s.SocketPath, err)
		}
		if err := os.Chmod(s.SocketPath, 0o600); err != nil {
			_ = ln.Close()
			for _, prev := range out {
				_ = prev.Close()
			}
			return nil, fmt.Errorf("chmod %s: %w", s.SocketPath, err)
		}
		out = append(out, ln)
	}
	return out, nil
}

func (s *Server) handleSnapshot(w http.ResponseWriter, r *http.Request) {
	if s.Store == nil {
		writeJSONError(w, http.StatusServiceUnavailable, "snapshot store not configured")
		return
	}
	snap, ok := s.Store.Latest()
	if !ok {
		writeJSONError(w, http.StatusServiceUnavailable, "snapshot not yet available")
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	_ = json.NewEncoder(w).Encode(snap)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeJSONError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}
