package main

func workflowV2CommandHelpCatalog() []commandHelp {
	common := []helpFlag{{Name: "--config", Value: "PATH", Description: "workflow v2 YAML config"}, {Name: "--var", Value: "KEY=VALUE", Description: "typed variable assignment; string_list values use JSON arrays; repeatable"}}
	selection := []helpFlag{{Name: "--id", Value: "ID", Description: "select an exact workflow run"}, {Name: "--config", Value: "PATH", Description: "select the newest run for this config"}}
	return []commandHelp{
		{Command: "workflow", Summary: "Run and manage persistent revision-aware DAG workflows.", Usage: []string{"tmact workflow example [--profile openspec]", "tmact workflow validate --config PATH [--var key=value] [--json]", "tmact workflow plan --config PATH [--var key=value] [--json]", "tmact workflow run --config PATH [--var key=value] [--once] [--execute]", "tmact workflow start --config PATH [--var key=value] [--execute] [--json]", "tmact workflow status (--id ID | --config PATH) [--json]", "tmact workflow wait (--id ID | --config PATH) [--timeout D] [--json]", "tmact workflow logs (--id ID | --config PATH) [--follow]", "tmact workflow pause|resume (--id ID | --config PATH)", "tmact workflow acknowledge (--id ID | --config PATH) [--stage STAGE]", "tmact workflow retry --id ID --stage STAGE", "tmact workflow resolve --id ID --stage STAGE --outcome OUTCOME [--input key=value]", "tmact workflow report --dispatch-id ID --outcome OUTCOME [--body TEXT] [--findings-file PATH]", "tmact workflow plan-report --dispatch-id ID --file PATH", "tmact workflow stop (--id ID | --config PATH) --wait"}, Subcommands: []string{"example", "validate", "plan", "run", "start", "status", "wait", "logs", "pause", "resume", "acknowledge", "retry", "resolve", "report", "plan-report", "stop"}, Safety: []string{"run and start only perform commands or tmux side effects when --execute is supplied.", "Permission and approval prompts are never accepted automatically.", "agent_dev only auto-selects Claude's exact preselected session-limit wait option; Codex waits are passive and never select upgrades or credit purchases."}, Notes: []string{"State and immutable config snapshots live under .tmact/workflows/<run-id>/.", "Agent reports use runner-issued durable dispatch IDs; agents never supply stage, attempt, or revision bindings.", "Claude and Codex usage-limit waits persist reset_at and resume the same dispatch/session/attempt after reset."}},
		{Command: "workflow example", Summary: "Print a generic workflow v2 YAML or a built-in profile.", Usage: []string{"tmact workflow example [--profile openspec|agent-dev]"}, Flags: []helpFlag{{Name: "--profile", Value: "NAME", Description: "print the openspec or agent-dev profile"}}, Examples: []string{"tmact workflow example > workflow.yaml", "tmact workflow example --profile agent-dev > agent-dev-workflow.yaml", "tmact workflow validate --config agent-dev-workflow.yaml --var request='implement the feature'", "tmact workflow example --profile openspec > openspec-workflow.yaml"}, Notes: []string{"agent-dev is a serialized coordinator/implementer/reviewer phase loop with Git work-item contracts.", "The OpenSpec profile defaults verification_argv to [\"go\", \"test\", \"./...\"] and verification_cwd to \".\"."}},
		{Command: "workflow validate", Summary: "Strictly validate workflow v2 YAML, variables, references, conditions, and DAG shape.", Usage: []string{"tmact workflow validate --config PATH [--var key=value] [--json]"}, Flags: append(common, helpFlag{Name: "--json", Description: "print machine-readable validation output"})},
		{Command: "workflow plan", Summary: "Compute revisions and print the side-effect-free execution plan.", Usage: []string{"tmact workflow plan --config PATH [--var key=value] [--json]"}, Flags: append(common, helpFlag{Name: "--json", Description: "print machine-readable plan"})},
		{Command: "workflow run", Summary: "Run a workflow in the foreground; without --execute only print its plan.", Usage: []string{"tmact workflow run --config PATH [--var key=value] [--once] [--execute]"}, Flags: append(common, helpFlag{Name: "--once", Description: "perform one scheduler pass"}, helpFlag{Name: "--execute", Description: "perform command and tmux side effects"})},
		{Command: "workflow start", Summary: "Idempotently start a live workflow in the detached tmact-workflows session.", Usage: []string{"tmact workflow start --config PATH [--var key=value] [--execute] [--json]"}, Flags: append(common, helpFlag{Name: "--execute", Description: "create the detached runner and allow live effects"}, helpFlag{Name: "--json", Description: "print machine-readable start result with run_id"})},
		{Command: "workflow status", Summary: "Show persisted run and stage state.", Usage: []string{"tmact workflow status (--id ID | --config PATH) [--json]"}, Flags: append(selection, helpFlag{Name: "--json", Description: "print JSON"})},
		{Command: "workflow wait", Summary: "Block until a workflow reaches a terminal or needs-user state.", Usage: []string{"tmact workflow wait (--id ID | --config PATH) [--timeout D] [--poll-interval D] [--json]"}, Flags: append(selection, helpFlag{Name: "--timeout", Value: "DURATION", Description: "give up after this long; 0 waits forever"}, helpFlag{Name: "--poll-interval", Value: "DURATION", Description: "state re-read interval; default 2s"}, helpFlag{Name: "--json", Description: "print final run_id/status/reason as JSON"}), Notes: []string{"Exits zero on succeeded or stopped; non-zero on failed, blocked, needs_user, or timeout."}},
		{Command: "workflow logs", Summary: "Read or follow durable workflow events.", Usage: []string{"tmact workflow logs (--id ID | --config PATH) [--follow]"}, Flags: append(selection, helpFlag{Name: "--follow", Description: "follow new events"})},
		{Command: "workflow pause", Summary: "Cooperatively pause scheduling new workflow stages.", Usage: []string{"tmact workflow pause (--id ID | --config PATH)"}, Flags: selection},
		{Command: "workflow resume", Summary: "Resume a paused or prompt-blocked workflow.", Usage: []string{"tmact workflow resume (--id ID | --config PATH)"}, Flags: selection, Safety: []string{"Handle and clear any permission or confirmation prompt before resuming. An active agent_dev dispatch is preserved and will block again if its prompt remains."}},
		{Command: "workflow acknowledge", Summary: "Unblock a blocked agent_dev stage while preserving its active dispatch.", Usage: []string{"tmact workflow acknowledge (--id ID | --config PATH) [--stage STAGE]"}, Flags: append(selection, helpFlag{Name: "--stage", Value: "STAGE", Description: "blocked agent_dev stage; required when several are blocked"}), Safety: []string{"Handle the prompt or condition that blocked the stage first. The next scheduler tick re-captures the pane and blocks again if it remains."}, Notes: []string{"Unlike resume it never resets stages to pending; unlike retry it keeps the dispatch, Git baseline, and report contract, and restarts the stage timeout window."}},
		{Command: "workflow retry", Summary: "Retry one stage and invalidate its downstream stages.", Usage: []string{"tmact workflow retry --id ID --stage STAGE"}, Flags: []helpFlag{{Name: "--id", Value: "ID", Required: true, Description: "workflow run id"}, {Name: "--stage", Value: "STAGE", Required: true, Description: "stage id"}}},
		{Command: "workflow resolve", Summary: "Resolve a waiting human stage with a structured outcome and input.", Usage: []string{"tmact workflow resolve --id ID --stage STAGE --outcome OUTCOME [--input key=value]"}, Flags: append(selection, helpFlag{Name: "--stage", Value: "STAGE", Required: true, Description: "human stage"}, helpFlag{Name: "--outcome", Value: "OUTCOME", Required: true, Description: "allowed outcome"}, helpFlag{Name: "--input", Value: "KEY=VALUE", Description: "schema-checked input; repeatable"})},
		{Command: "workflow report", Summary: "Record an agent outcome for one durable dispatch ID.", Usage: []string{"tmact workflow report --dispatch-id ID --outcome OUTCOME [--body TEXT] [--findings-file PATH]"}, Flags: []helpFlag{{Name: "--dispatch-id", Value: "ID", Required: true, Description: "runner-issued durable dispatch id"}, {Name: "--outcome", Value: "OUTCOME", Required: true, Description: "stage-allowlisted outcome"}, {Name: "--body", Value: "TEXT", Description: "short evidence summary"}, {Name: "--findings-file", Value: "PATH", Description: "structured agent_dev reviewer findings"}}},
		{Command: "workflow plan-report", Summary: "Submit one coordinator phase or fix plan for an active agent_dev dispatch.", Usage: []string{"tmact workflow plan-report --dispatch-id ID --file PATH [--store-dir PATH]"}, Flags: []helpFlag{{Name: "--dispatch-id", Value: "ID", Required: true, Description: "active coordinator dispatch id"}, {Name: "--file", Value: "PATH", Required: true, Description: "JSON phase plan"}, {Name: "--store-dir", Value: "PATH", Description: "workflow state root"}}},
		{Command: "workflow stop", Summary: "Request cooperative shutdown and wait for the runner.", Usage: []string{"tmact workflow stop (--id ID | --config PATH) --wait"}, Flags: append(selection, helpFlag{Name: "--wait", Required: true, Description: "wait for terminal state"})},
	}
}
