#!/usr/bin/env python3
"""Subset Maple Mono CN into chunked woff2 files for the pane font picker.

Maple Mono CN draws CJK at exactly two Latin cells, so Chinese inside agent
TUI frames lines up. The full TTF is ~20 MB per weight, so this keeps Latin +
the terminal symbol blocks + Big5 (常用/次常用 Traditional Chinese) + GB2312
level 1 (common Simplified) and splits the CJK part into unicode-range chunks:
the browser only downloads the chunks whose characters are on screen.
Anything outside the subset falls back to the system CJK font.

Usage (needs fonttools[woff]; uv fetches it on the fly):

  uvx --from 'fonttools[woff]' python scripts/subset-maple-cn.py \
      MapleMono-CN-Regular.ttf MapleMono-CN-Bold.ttf

Source TTFs: MapleMono-CN-unhinted.zip from
https://github.com/subframe7536/maple-font/releases (SIL OFL 1.1).
Writes src/fonts/maple-cn/*.woff2 and src/fonts/maple-cn/maple-cn.css. The
output must stay byte-stable for unchanged input: the woff2 names are hashed
into /assets/, and clients cache each hashed chunk forever.
"""

import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "fonts", "maple-cn")
CJK_CHUNK = 600

BASE_RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x017F),  # Latin-1 + Latin Extended-A
    (0x02C6, 0x02DD),  # spacing modifiers (ˆ ˜ etc.)
    (0x0391, 0x03C9),  # Greek
    (0x2000, 0x206F),  # General Punctuation
    (0x20A0, 0x20BF),  # currency
    (0x2100, 0x214F),  # letterlike
    (0x2150, 0x218F),  # number forms
    (0x2190, 0x21FF),  # arrows
    (0x2200, 0x22FF),  # math operators
    (0x2300, 0x23FF),  # misc technical (⏺ ⎿ …)
    (0x2460, 0x24FF),  # enclosed alphanumerics
    (0x2500, 0x257F),  # box drawing
    (0x2580, 0x259F),  # block elements
    (0x25A0, 0x25FF),  # geometric shapes
    (0x2600, 0x26FF),  # misc symbols
    (0x2700, 0x27BF),  # dingbats
    (0x2800, 0x28FF),  # braille (spinners)
    (0xE0A0, 0xE0D7),  # powerline
]
CJK_SYMBOL_RANGES = [
    (0x3000, 0x303F),  # CJK symbols & punctuation
    (0x3100, 0x312F),  # bopomofo
    (0xFF00, 0xFFEF),  # half/fullwidth forms
]


def big5_codepoints():
    # Big5 byte order puts the 5401 常用字 (A440–C67E) before 次常用字, so
    # chunking in this order keeps everyday text inside the first ~9 chunks.
    cps = {}
    for hi in range(0xA1, 0xFA):
        for lo in list(range(0x40, 0x7F)) + list(range(0xA1, 0xFF)):
            try:
                ch = bytes([hi, lo]).decode("big5")
            except UnicodeDecodeError:
                continue
            cps.setdefault(ord(ch))
    return list(cps)


def gb2312_level1_codepoints():
    # GB2312 一級漢字 (B0A1–D7F9): the 3755 common Simplified characters.
    cps = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                cps.append(ord(bytes([hi, lo]).decode("gb2312")))
            except UnicodeDecodeError:
                continue
    return cps


def expand(ranges):
    return {cp for lo, hi in ranges for cp in range(lo, hi + 1)}


def unicode_range(cps):
    cps = sorted(cps)
    parts, start, prev = [], cps[0], cps[0]
    for cp in cps[1:] + [None]:
        if cp is not None and cp == prev + 1:
            prev = cp
            continue
        parts.append(f"U+{start:X}" if start == prev else f"U+{start:X}-{prev:X}")
        if cp is not None:
            start = prev = cp
    return ", ".join(parts)


def chunks(cmap_cps):
    base = expand(BASE_RANGES) & cmap_cps
    symbols = sorted(expand(CJK_SYMBOL_RANGES) & cmap_cps - base)
    seen = base | set(symbols)
    cjk = list(symbols)
    for cp in big5_codepoints() + gb2312_level1_codepoints():
        if cp in cmap_cps and cp not in seen:
            seen.add(cp)
            cjk.append(cp)
    yield "base", base
    for i in range(0, len(cjk), CJK_CHUNK):
        yield f"cjk{i // CJK_CHUNK:02d}", set(cjk[i : i + CJK_CHUNK])


def write_subset(src, cps, dst):
    font = TTFont(src)
    opts = subset.Options()
    opts.flavor = "woff2"
    opts.hinting = False
    opts.layout_features = ["*"]
    opts.name_IDs = ["*"]
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=cps)
    sub.subset(font)
    font.flavor = "woff2"
    font.save(dst)


def main(paths):
    os.makedirs(OUT_DIR, exist_ok=True)
    css = [
        "/* Generated by scripts/subset-maple-cn.py — do not edit. */",
        "/* Maple Mono CN, SIL OFL 1.1 (see OFL.txt). */",
    ]
    for path in paths:
        weight = 700 if "Bold" in os.path.basename(path) else 400
        cmap_cps = set(TTFont(path).getBestCmap())
        for name, cps in chunks(cmap_cps):
            fname = f"maple-mono-cn-{weight}-{name}.woff2"
            write_subset(path, cps, os.path.join(OUT_DIR, fname))
            css += [
                "@font-face {",
                '  font-family: "Maple Mono CN";',
                "  font-style: normal;",
                f"  font-weight: {weight};",
                "  font-display: swap;",
                f'  src: url("./{fname}") format("woff2");',
                f"  unicode-range: {unicode_range(cps)};",
                "}",
            ]
            print(fname, len(cps), os.path.getsize(os.path.join(OUT_DIR, fname)))
    with open(os.path.join(OUT_DIR, "maple-cn.css"), "w") as f:
        f.write("\n".join(css) + "\n")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    main(sys.argv[1:])
